// Regenerates components/brand/logoSvg.generated.ts from public/brand/nadoch-logo.svg (spec: Brand).
// The SVG file is the single source of truth and is never edited; the module holds its exact text,
// so the logo can render inline in client components too. Logo.test.tsx fails if the two drift.
// Run: npx tsx scripts/build-logo.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const svg = readFileSync(join(root, 'public', 'brand', 'nadoch-logo.svg'), 'utf8');
const out = `// Generated by scripts/build-logo.ts from public/brand/nadoch-logo.svg. Do not edit by hand.
export const LOGO_SVG = ${JSON.stringify(svg)};
`;
writeFileSync(join(root, 'components', 'brand', 'logoSvg.generated.ts'), out);
